version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5555:80
        volumes:
            - ./src:/var/www/html

    db:
        image: mysql
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8080:3306

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1